name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        ./node_modules/.bin/parcel build src/*.html --public-url https://dhes.github.com/my-health-data
    - name: deploy
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(matrix.node-version, '12')
      run: |
        git config user.email "drdan@heslingamd.com"
        git config user.name "GitHub Actions"
        git checkout gh-pages
        git rm *.html *.js *.map
        cp -r dist/* .
        git add *.js *.html *.map
        git commit -m "Build"
        git remote add
        git push -u gh-pages
